SET(RP4_SDK_ROOT /home/ikrechetov/projects/rp4_qt)
SET(RP4_SDK_TOOLCHAIN gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf)
set(ENV{PKG_CONFIG_PATH} "${RP4_SDK_ROOT}/sysroot/lib/arm-linux-gnueabihf/pkgconfig")

SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSROOT ${RP4_SDK_ROOT}/sysroot)
SET(CMAKE_FIND_ROOT_PATH ${RP4_SDK_ROOT}/tools/${RP4_SDK_TOOLCHAIN})

# set(CMAKE_INSTALL_RPATH ${CMAKE_SYSROOT}/usr/lib/arm-linux-gnueabihf)
SET(CMAKE_C_COMPILER ${CMAKE_FIND_ROOT_PATH}/bin/arm-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER ${CMAKE_FIND_ROOT_PATH}/bin/arm-linux-gnueabihf-g++)

# set(CMAKE_C_STANDARD_INCLUDE_DIRECTORIES ${CMAKE_SYSROOT}/usr/include)
# set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES ${CMAKE_SYSROOT}/usr/include)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_PREFIX_PATH ${CMAKE_SYSROOT})